- name: nginx install and run
  hosts: web
  become: yes #to run as root
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterongenous module that can work for all distros
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.services:
      name: nginx
      state: started
      enabled: yes
