- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy"
    var_files:
    - vars.yaml
    vars_prompt:
    - name: COURSE
      PROMPT: Please enter the course name
      private: false
    tasks:
    - name: print the information
      vars:
        COURSE: "DevOps with AES from TASK level"
        DURATION: "120HRS"
        TRAINER: "Sivakumar Reddy"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}"
